name: Benchmarks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true # 'bundle install' and cache
    - name: Run Benchmarks
      run: RUBY_YJIT_ENABLE=1 BENCH_TARGET=all bundle exec bundle exec bin/benchmark
