inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25

ThreadSafety/ClassInstanceVariable:
  Enabled: true
  Exclude:
    - "**/*.gemspec"
    # exclude tests from thread safety checks
    - test/**/*

ThreadSafety/NewThread:
  Exclude:
    # Tests need to create threads to test concurrent behavior
    - test/**/*

ThreadSafety/MutableClassInstanceVariable:
  Exclude:
    # Test utilities need mutable class variables
    - test/**/*

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
